### ISSUE TITLE
Multiple loads in millis

### ISSUE THREAD

**Issue by BsAtHome** [nerdralph/ArduinoShrink#4]
Hi,

You reload the timer value in a call to millis() when a timer interrupt changes the value. Although this will (very sightly) improve interrupt service timing stability. Why not use:
```
millis():
  ldi ZL, lo8(t0_millis)
  ldi ZH, hi8(t0_millis)
  in r0, SREG
  cli
  ld r22, Z+
  ld r23, Z+
  ld r24, Z+
  ld r25, Z
  out SREG, r0
  ret
```
This would give worst case extra 5 clock cycle delay in interrupt service timing. That should be reasonable and no extra jumps are introduced (the millis() function becomes constant in time).

**Comment by nerdralph** [comment]
You've misunderstood the asm cycle timing.  ld takex 2 cycles, not one.  The instruction after the I bit is set also runs before any pending interrupts, adding an extra 4 cycles of interrupt latency for the ret instruction.  Your suggestion would impact interrupt latency up to 13 cycles.

Having constant time interrupts with low latency is far more important than a constant time millis.
