### ISSUE TITLE
__vector_16 multiple definition error

### ISSUE THREAD

**Issue by ZachEnglish** [nerdralph/ArduinoShrink#7]
Arduino IDE 1.8.13 on a Raspberry Pi 4. Tried pulling in ArduinoShrink and compilation gives me this error:

tmp/cc3bYbis.ltrans0.ltrans.o: In function `__vector_16':
/opt/arduino-1.8.13/hardware/arduino/avr/cores/arduino/wiring.c:47: multiple definition of `__vector_16'
libraries/ArduinoShrink-0.6.0/ArduinoShrink-0.6.0.a(t0_ovfl_isr.S.o):/home/pi/Arduino/libraries/ArduinoShrink-0.6.0/src/t0_ovfl_isr.S:29: first defined here

Any help would be appreciated! Let me know if you need more details.

**Comment by ZachEnglish** [comment]
wiring.c.o (symbol from plugin): In function `__vector_16':
(.text+0x0): multiple definition of `__vector_16'
libraries/ArduinoShrink-0.6.0/ArduinoShrink-0.6.0.a(t0_ovfl_isr.S.o):/home/pi/Arduino/libraries/ArduinoShrink-0.6.0/src/t0_ovfl_isr.S:29: first defined here
wiring.c.o (symbol from plugin): In function `__vector_16':
(.text+0x0): multiple definition of `millis'
millis.c.o (symbol from plugin):(.text+0x0): first defined here
wiring.c.o (symbol from plugin): In function `__vector_16':
(.text+0x0): multiple definition of `micros'
millis.c.o (symbol from plugin):(.text+0x0): first defined here
wiring.c.o (symbol from plugin): In function `__vector_16':
(.text+0x0): multiple definition of `delayMicroseconds'
wiring.c.o (symbol from plugin):(.text+0x0): first defined here
wiring.c.o (symbol from plugin): In function `__vector_16':
(.text+0x0): multiple definition of `init'
wiring.c.o (symbol from plugin):(.text+0x0): first defined here

**Comment by nerdralph** [comment]
Can you copy the build line after "Using library ArduinoShrink"?  It looks
like the IDE isn't building core.a to link to the sketch code.  I'll also
install the IDE on my Ubuntu box to see if it does the same thing.

**Comment by nerdralph** [comment]
I just tested with arduino-1.8.13-linux64 and it works fine.  When you say you're running 1.8.13 on the Pi, did you download arduino-1.8.13-linuxaarch64?  I don't have a Pi 4 to test with, but I do have a Pi Zero I may be able to install the IDE on.

**Comment by ZachEnglish** [comment]
Thanks for the quick replies!

I tried to help narrow down the problem. On the Pi I built Blink with ArduinoShrink and it worked just fine, so I think the library is hooked in properly.

I pulled ArduinoShrink onto my Windows 10 box and Blink worked there as well but my project had the same errors. Something I'm using/doing is causing it issues....

I'll admit, I have a LOT of libraries going on. The project is [(https://github.com/ZachEnglish/NanoProtoShield)] and can be found in the Arduino Library Manager if you want to try building it yourself. Please ignore my C++ warnings! ;-) (the VerifyBoard example sketch is the biggie to get working but even simple ones like RotaryLight have the issue. An Arduino Nano is the target board and the processor is the "328P old bootloader" one.

I was very interested in your project because the board I built up has a lot of accessories on it and getting off the shelf libraries to talk to all the components has left me very little room for program storage and dynamic memory. I've tried to cut down my memory footprint by only enabling accessories in use, but when they all get used (as in VerifyBoard), I start overflowing the stack regularly (the 128x64 display alone takes up half the 2K available when enabled).

You are welcome to poke around or ask me to try other things. I am very excited by your project!

**Comment by ZachEnglish** [comment]
Hmmmm, I noticed you said this library may not work if the pin number for digitalWrite() isn't known at compile time. I definitely have that situation in my library. Did a quick test modifying a compiling version of Blink to use digitalWrite(millis()...) and it compiled just fine. Sure it wouldn't work, but it doesn't seem like that would throw these errors while building.

**Comment by nerdralph** [comment]
That actually helps a lot, and helped me recognize a possible bug with how
I implemented delay().  The fix should be relatively simple.

**Comment by nerdralph** [comment]
I think issue #8 may be the same problem you are encountering.

**Comment by ZachEnglish** [comment]
I have confirmed version 0.6.1 fixes the issue and lets my project build. Thank you so much!

**Comment by ZachEnglish** [comment]
As a point of reference and testimonial, this library saves my project 774 bytes of program memory and 3 bytes of dynamic memory.

The digitalWrite() failure when unable to resolve at compile time is pretty silent. No compiler warnings or errors, it just doesn't run. Log that under "minor improvement" :-)

Thanks again!

**Comment by nerdralph** [comment]
digitalWrite() should function properly in all cases now, without sacrificing the optimized version when the pin is known at compile time.

**Comment by ZachEnglish** [comment]
Gave it one quick test and my Verify Board example sketch still does not work with 0.7.0 (builds and uploads but does not interface with RGB LEDs or my OLED display over I2C), though I haven't dug into it at all yet. I will try to do that in the next few days and report back my findings.

**Comment by nerdralph** [comment]
I did some additional testing with multiple libraries, and figured out that the Arduino IDE uses the order of #include statements to determine library link order.  ArduinoShrink must be the last library on the link line before core.a, and so it must also be the last library include.  I've updated the README to mention this requirement.
